#define RVLRECOGNITION_MODE_RECOGNITION			0
#define RVLRECOGNITION_MODE_TRAINING			1
#define RVLRECOGNITION_PROBLEM_SHAPE_INSTANCE_DETECTION		0
#define RVLRECOGNITION_PROBLEM_CLASSIFICATION				1
#define RVLRECOGNITION_PROBLEM_PART_SEGMENTATION			2
#define RVLRECOGNITION_PROBLEM_TORUS_DETECTION				3
#define RVLRECOGNITION_METHOD_RF		0
#define RVLRECOGNITION_METHOD_PSGM		1
#define RVLRECOGNITION_METHOD_VN		2
#define RVLRECOGNITION_METHOD_TG		3
#define RVLRECOGNITION_METHOD_DDD		4
#define RVLRECOGNITION_METHOD_BM		5
#define RVLRECOGNITION_METHOD_CGSP		6

