float64 w_door
float64 h_door
float64 d_door
float64 rx
float64 ry
float64 static_side_width
float64 axis_distance
float64 moving_to_static_part_distance
int32 axis_pos
float64[] T_A_S
float64[] T_R_W
float64[] q_init
float64 start_angle
float64 target_angle
int32 num_states
---
bool success
float64[] joint_trajectory
int32 num_points